service: my-service

provider:
  name: aws
  runtime: python3.9
  region: us-west-2
  stage: dev

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:GetItem
            - dynamodb:Query
          Resource:
            - arn:aws:dynamodb:us-west-2:982081078723:table/YourDynamoDBTableName  # Replace with your table name
        - Effect: Allow
          Action:
            - ses:SendEmail
            - ses:SendRawEmail
          Resource: "*"

functions:
  subscribe_user:
    handler: handler.subscribe_user  # Existing handler in handler.py
    memorySize: 1024
    timeout: 30
    events:
      - http:
          path: subscribe
          method: post
          cors:
            origin: '*'  
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false

  register_user:
    handler: handler.register_user  # Existing handler in handler.py
    memorySize: 1024
    timeout: 30
    events:
      - http:
          path: register
          method: post
          cors:
            origin: '*'   
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false

  fetch_questions:
    handler: trainques.fetch_questions  # New handler in trainques.py
    memorySize: 1024
    timeout: 30
    events:
      - http:
          path: questions
          method: get
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false

plugins:
  - serverless-python-requirements
  - serverless-offline
